name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js v22
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Install Compact Compiler
        run: curl --proto '=https' --tlsv1.2 -LsSf https://github.com/midnightntwrk/compact/releases/latest/download/compact-installer.sh | sh

      - name: Compile Contract
        run: |
          $HOME/.local/bin/compact update
          $HOME/.local/bin/compact compile contracts/voting.compact public/keys
          $HOME/.local/bin/compact compile contracts/voting.compact src/services/midnight/managed/voting

      - name: Run test suite
        run: npm test
